name: Portfolio Website CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker Image
      run: docker build -t portfolio-website .
    
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push to Docker Hub
      run: |
        docker tag portfolio-website ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:latest
